
[workspace]
resolver = "2"
members = ["day01", "day02", "day03", "day04", "day05"]

[build]
rustflags = ["-C", "target-cpu=native"]

[workspace.metadata.aoch]
year = 2023

[patch."https://github.com/chrismooredev/aochelper"]
aoch = { path = "C:/Users/cmoore79/Documents/projects/aochelper" }
